name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linting
        run: |
          flake8 && isort --check --diff . && mypy
      - name: Security check
        run: |
          bandit -r .
      - name: Run uvicorn
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      - name: Test with pytest
        run: |
          pytest .
